spring.application.name=simple-nms-gateway

server.port=8082

spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=simple-nms
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*

# JWT config (REQUIRED)
jwt.secret=mysupersecretkeymysupersecretkey